# Generated by Django 5.2 on 2025-04-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contract_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
