# Generated by Django 5.2 on 2025-04-16 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_customuser_contract_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('window_number', models.PositiveIntegerField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kundalik Ish Oynasi',
                'verbose_name_plural': 'Kundalik Ish Oynalari',
                'unique_together': {('operator', 'date')},
            },
        ),
    ]
