# Generated by Django 5.2 on 2025-04-16 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_dailyworkwindow'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('newbie', 'Yangi operator'), ('standard', 'Oddiy operator'), ('premium', 'Premium operator'), ('vip', 'VIP operator')], default='newbie', max_length=20)),
                ('total_served', models.PositiveIntegerField(default=0)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
