# Generated by Django 5.2 on 2025-04-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_operatorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkwindow',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
