# Generated by Django 5.2 on 2025-04-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_operatorprofile_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkwindow',
            name='window_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
