# Generated by Django 5.2 on 2025-04-15 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0001_initial'),
        ('registrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AlterField(
            model_name='queueticket',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='registrator.subservice'),
        ),
        migrations.AlterModelOptions(
            name='queueticket',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='queueticket',
            name='user',
        ),
        migrations.AlterField(
            model_name='queueticket',
            name='status',
            field=models.CharField(choices=[('waiting', 'Kutmoqda'), ('serving', 'Xizmat ko‘rsatilmoqda'), ('done', 'Yakunlangan')], default='waiting', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
