# Generated by Django 5.2 on 2025-04-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0003_queueticket_ended_at_queueticket_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueticket',
            name='ticket_number',
            field=models.CharField(max_length=10),
        ),
    ]
