# Generated by Django 5.2 on 2025-04-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0004_alter_queueticket_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueticket',
            name='window_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Oyna raqami'),
        ),
    ]
